export const mockAuctions = [
  // {
  //   _id: "683430072c328fb5be79da3e",
  //   id: 1,
  //   itemName: "Vintage Camera",
  //   itemDescription: "A beautiful vintage camera from the 1960s in excellent condition",
  //   itemCategory: "Electronics",
  //   itemPhoto: "",
  //   startingPrice: 100,
  //   currentPrice: 250,
  //   itemStartDate: new Date("2024-01-15"),
  //   itemEndDate: new Date("2024-02-15"),
  //   seller: { _id: "seller1", name: "John Doe" },
  //   bids: [
  //     { bidder: { name: "Alice" }, bidAmount: 200, bidTime: new Date() },
  //     { bidder: { name: "Bob" }, bidAmount: 250, bidTime: new Date() },
  //   ],
  //   isSold: false,
  //   createdAt: new Date("2024-01-15"),
  // },
  // {
  //   _id: "683430072c328fb5be79da3e",
  //   id: 2,
  //   itemName: "Antique Vase",
  //   itemDescription: "Rare Ming dynasty vase with intricate patterns",
  //   itemCategory: "Antiques",
  //   itemPhoto: "",
  //   startingPrice: 500,
  //   currentPrice: 1200,
  //   itemStartDate: new Date("2024-01-10"),
  //   itemEndDate: new Date("2024-02-10"),
  //   seller: { _id: "seller2", name: "Jane Smith" },
  //   bids: [
  //     { bidder: { name: "Charlie" }, bidAmount: 800, bidTime: new Date() },
  //     { bidder: { name: "Diana" }, bidAmount: 1200, bidTime: new Date() },
  //   ],
  //   isSold: false,
  //   createdAt: new Date("2024-01-10"),
  // },
  // {
  //   _id: "683430072c328fb5be79da3e",
  //   id: 3,
  //   itemName: "Classic Guitar",
  //   itemDescription: "Fender Stratocaster 1970s model in mint condition",
  //   itemCategory: "Musical Instruments",
  //   itemPhoto: "",
  //   startingPrice: 800,
  //   currentPrice: 800,
  //   itemStartDate: new Date("2024-01-20"),
  //   itemEndDate: new Date("2024-02-20"),
  //   seller: { _id: "seller3", name: "Mike Johnson" },
  //   bids: [],
  //   isSold: false,
  //   createdAt: new Date("2024-01-20"),
  // },
  // {
  //   _id: "683430072c328fb5be79da3e",
  //   id: 4,
  //   itemName: "Classic Guitar",
  //   itemDescription: "Fender Stratocaster 1970s model in mint condition",
  //   itemCategory: "Musical Instruments",
  //   itemPhoto: "",
  //   startingPrice: 800,
  //   currentPrice: 800,
  //   itemStartDate: new Date("2024-01-20"),
  //   itemEndDate: new Date("2024-02-20"),
  //   seller: { _id: "seller3", name: "Mike Johnson" },
  //   bids: [],
  //   isSold: false,
  //   createdAt: new Date("2024-01-20"),
  // },
]